import {
  BadRequestException,
  ConflictException,
  HttpException,
  HttpStatus,
  Inject,
  Injectable,
  Logger,
  NotFoundException,
  type OnApplicationBootstrap,
  type OnModuleDestroy,
} from '@nestjs/common';
import { sql, type Transaction } from 'kysely';
import {
  costMicros,
  createDraftProvider,
  MAX_DISH_NAME,
  MAX_PREFERENCES,
  modelPrice,
  ProviderError,
  worstCaseMicros,
  type DraftProvider,
  type ProviderReply,
} from './ai-providers.js';
import { APP_CONFIG, type AiConfig, type AppConfig } from './config.js';
import { DatabaseService, type AiDraftErrorCode, type Database } from './database.service.js';
import { HouseholdsService } from './households.service.js';
import { parseRecipeInput, RecipesService, type RecipeInput } from './recipes.service.js';
import { isUuid } from './security.js';

/** Serializes quota and budget checks across concurrent requests (and application instances). */
const RESERVATION_LOCK = 7_300_006;
/** A job that could not start within this time is failed; it was never sent to the provider. */
const QUEUE_EXPIRY_SECONDS = 300;
const POLL_INTERVAL_MS = 5000;
const WARNING_SHARE = 0.8;

const ERROR_MESSAGES: Record<AiDraftErrorCode, string> = {
  timeout: 'The AI service took too long to answer.',
  provider_error: 'The AI service could not be reached or returned an error.',
  invalid_output: 'The AI service returned a draft that was not a usable recipe.',
  refused: 'The AI service declined to write this recipe.',
  interrupted: 'The draft was interrupted before it finished.',
  expired: 'The draft waited too long to start.',
};

export interface DraftCreateInput {
  requestId: string;
  dishName: string;
  preferences: string;
}

function fail(message: string): never {
  throw new BadRequestException(message);
}

export function parseDraftCreate(body: unknown): DraftCreateInput {
  const input = (body ?? {}) as Record<string, unknown>;
  if (typeof input.requestId !== 'string' || !isUuid(input.requestId)) {
    fail('requestId must be a UUID generated by the client for this request.');
  }
  if (typeof input.dishName !== 'string' || !input.dishName.trim()) fail('dishName is required.');
  const dishName = input.dishName.trim();
  if (dishName.length > MAX_DISH_NAME) {
    fail(`dishName must be at most ${MAX_DISH_NAME} characters.`);
  }
  const rawPreferences = input.preferences ?? '';
  if (typeof rawPreferences !== 'string') fail('preferences must be text.');
  const preferences = rawPreferences.trim();
  if (preferences.length > MAX_PREFERENCES) {
    fail(`preferences must be at most ${MAX_PREFERENCES} characters.`);
  }
  return { requestId: input.requestId.toLowerCase(), dishName, preferences };
}

function refuse(status: HttpStatus, code: string, message: string): never {
  throw new HttpException({ statusCode: status, message, code }, status);
}

type DraftRow = {
  id: string;
  status: 'queued' | 'running' | 'succeeded' | 'failed';
  dishName: string;
  preferences: string;
  model: string;
  errorCode: AiDraftErrorCode | null;
  draft: Omit<RecipeInput, 'pricePoints'> | null;
  savedRecipeId: string | null;
  discardedAt: Date | null;
  createdAt: Date;
  finishedAt: Date | null;
  createdBy: string;
};

/**
 * Quota-limited AI recipe drafts (MVP_SPEC "AI draft workflow", AC-06, AC-13).
 *
 * A request is accepted only after, under one database lock: the household's recent drafts, the
 * person's recent attempts, and this month's provider spend plus the new worst-case reservation
 * are all within their limits. The job is stored before any provider call, so a crash leaves a
 * recoverable row. An in-process worker claims queued jobs with SKIP LOCKED and a lease. A job
 * whose lease expires is failed as interrupted and is not retried, because the provider may
 * already have billed it; its reservation stays counted.
 *
 * Drafts stay drafts: nothing reaches the household menu until a member saves one, and each
 * draft can be saved at most once.
 */
@Injectable()
export class AiDraftsService implements OnApplicationBootstrap, OnModuleDestroy {
  private readonly logger = new Logger('AiDrafts');
  private readonly config: AiConfig | undefined;
  private readonly provider: DraftProvider | undefined;
  private readonly reservationMicros: number;
  private readonly price: { input: number; output: number } | undefined;
  private inFlight = 0;
  private timer: NodeJS.Timeout | undefined;
  private readonly shutdown = new AbortController();
  private readonly running = new Set<Promise<void>>();

  constructor(
    @Inject(APP_CONFIG) appConfig: AppConfig,
    private readonly database: DatabaseService,
    private readonly households: HouseholdsService,
    private readonly recipes: RecipesService,
  ) {
    this.config = appConfig.ai;
    this.provider = this.config ? createDraftProvider(this.config) : undefined;
    this.price = this.config ? modelPrice(this.config) : undefined;
    this.reservationMicros = this.price ? worstCaseMicros(this.price) : 0;
  }

  /** The active provider; tests use it to script the mock. */
  get activeProvider() {
    return this.provider;
  }

  onApplicationBootstrap() {
    if (!this.provider) return;
    this.timer = setInterval(() => this.tick(), POLL_INTERVAL_MS);
    this.timer.unref();
    this.tick();
  }

  async onModuleDestroy() {
    clearInterval(this.timer);
    this.shutdown.abort(new Error('Application shutting down.'));
    await Promise.allSettled([...this.running]);
  }

  async overview(userId: string, householdId: string) {
    await this.households.requireMember(userId, householdId);
    await this.recoverStale();
    const drafts = await this.baseQuery()
      .where('d.household_id', '=', householdId)
      .where('d.saved_at', 'is', null)
      .where('d.discarded_at', 'is', null)
      .where('d.created_at', '>', sql<Date>`now() - interval '7 days'`)
      .orderBy('d.created_at', 'desc')
      .limit(10)
      .execute();
    let remaining = 0;
    if (this.config) {
      const used = await this.householdUsage(this.database.db, householdId);
      remaining = Math.max(0, this.config.householdDailyLimit - used);
    }
    return {
      enabled: this.config !== undefined,
      model: this.config?.model ?? null,
      householdDailyLimit: this.config?.householdDailyLimit ?? 0,
      remainingToday: remaining,
      drafts: drafts.map((row) => this.present(row)),
    };
  }

  async get(userId: string, householdId: string, draftId: string) {
    await this.households.requireMember(userId, householdId);
    await this.recoverStale();
    return this.present(await this.read(this.database.db, householdId, draftId));
  }

  async create(userId: string, householdId: string, input: DraftCreateInput) {
    const config = this.config;
    if (!config) {
      refuse(
        HttpStatus.SERVICE_UNAVAILABLE,
        'ai_disabled',
        'AI drafts are turned off. You can still add recipes by hand or from starter recipes.',
      );
    }
    const result = await this.database.db.transaction().execute(async (trx) => {
      await this.households.requireMember(userId, householdId, trx, true);
      await sql`select pg_advisory_xact_lock(${RESERVATION_LOCK})`.execute(trx);
      // A retried request (double tap, network retry) returns the first job without a new call.
      const existing = await trx
        .selectFrom('app.ai_draft_requests')
        .select('id')
        .where('household_id', '=', householdId)
        .where('create_request_id', '=', input.requestId)
        .executeTakeFirst();
      if (existing) return { id: existing.id, created: false };

      const used = await this.householdUsage(trx, householdId);
      if (used >= config.householdDailyLimit) {
        refuse(
          HttpStatus.TOO_MANY_REQUESTS,
          'household_limit',
          `Your household has used its ${config.householdDailyLimit} AI drafts for the last 24 hours. You can still add recipes by hand.`,
        );
      }
      const { attempts } = await trx
        .selectFrom('app.ai_draft_requests')
        .select(sql<number>`count(*)::int`.as('attempts'))
        .where('created_by', '=', userId)
        .where('created_at', '>', sql<Date>`now() - interval '24 hours'`)
        .executeTakeFirstOrThrow();
      if (attempts >= config.userDailyAttempts) {
        refuse(
          HttpStatus.TOO_MANY_REQUESTS,
          'user_limit',
          'You have made many AI draft requests recently. Please try again later.',
        );
      }
      const spent = await this.monthSpend(trx);
      if (spent + this.reservationMicros > config.monthlyBudgetMicros) {
        this.logger.warn(
          `AI monthly budget reached: ${spent} of ${config.monthlyBudgetMicros} micro-USD.`,
        );
        refuse(
          HttpStatus.SERVICE_UNAVAILABLE,
          'budget_exhausted',
          'AI drafts are paused for the rest of the month. You can still add recipes by hand.',
        );
      }
      if (spent + this.reservationMicros > config.monthlyBudgetMicros * WARNING_SHARE) {
        this.logger.warn(
          `AI spend is above ${WARNING_SHARE * 100}% of the monthly budget: ${spent} of ${config.monthlyBudgetMicros} micro-USD.`,
        );
      }
      const inserted = await trx
        .insertInto('app.ai_draft_requests')
        .values({
          household_id: householdId,
          created_by: userId,
          create_request_id: input.requestId,
          dish_name: input.dishName,
          preferences: input.preferences,
          provider: config.provider,
          model: config.model,
          reserved_micros: this.reservationMicros,
        })
        .returning('id')
        .executeTakeFirstOrThrow();
      return { id: inserted.id, created: true };
    });
    if (result.created) this.tick();
    return {
      created: result.created,
      draft: this.present(await this.read(this.database.db, householdId, result.id)),
    };
  }

  /** Saves the member's edited version of a finished draft as a household recipe, once. */
  async save(userId: string, householdId: string, draftId: string, input: RecipeInput) {
    return this.database.db.transaction().execute(async (trx) => {
      await this.households.requireMember(userId, householdId, trx, true);
      const draft = await this.lockDraft(trx, householdId, draftId);
      if (draft.saved_recipe_id)
        return this.recipes.detail(trx, householdId, draft.saved_recipe_id);
      if (draft.discarded_at) throw new ConflictException('This draft was discarded.');
      if (draft.status !== 'succeeded') {
        throw new ConflictException('This draft is not ready to save.');
      }
      // The draft id doubles as the recipe's idempotency key.
      const recipe = await this.recipes.insertRecipe(trx, userId, householdId, input, draftId, {
        source: 'ai',
        draftId,
      });
      await trx
        .updateTable('app.ai_draft_requests')
        .set({ saved_recipe_id: recipe.id, saved_by: userId, saved_at: sql<Date>`now()` })
        .where('id', '=', draftId)
        .execute();
      return recipe;
    });
  }

  /** Discarding never changes the menu. A job still running finishes but stays discarded. */
  async discard(userId: string, householdId: string, draftId: string) {
    await this.database.db.transaction().execute(async (trx) => {
      await this.households.requireMember(userId, householdId, trx, true);
      const draft = await this.lockDraft(trx, householdId, draftId);
      if (draft.saved_recipe_id) throw new ConflictException('This draft was already saved.');
      if (draft.discarded_at) return;
      await trx
        .updateTable('app.ai_draft_requests')
        .set({ discarded_by: userId, discarded_at: sql<Date>`now()` })
        .where('id', '=', draftId)
        .execute();
    });
    return this.present(await this.read(this.database.db, householdId, draftId));
  }

  /** Recovers stale jobs, then starts queued ones up to the concurrency limit. */
  tick() {
    if (!this.provider || !this.config || this.shutdown.signal.aborted) return;
    const work = this.recoverStale()
      .then(() => this.fill())
      .catch((error: unknown) => {
        this.logger.error(`AI worker tick failed: ${(error as Error).message}`);
      });
    this.track(work);
  }

  private async fill() {
    while (this.inFlight < this.config!.concurrency && !this.shutdown.signal.aborted) {
      this.inFlight += 1;
      const job = await this.claim().catch((error: unknown) => {
        this.inFlight -= 1;
        throw error;
      });
      if (!job) {
        this.inFlight -= 1;
        return;
      }
      this.track(
        this.run(job)
          .catch((error: unknown) => {
            // The row keeps its lease and is recovered as interrupted.
            this.logger.error(
              `AI draft ${job.id} could not be recorded: ${(error as Error).message}`,
            );
          })
          .finally(() => {
            this.inFlight -= 1;
            this.tick();
          }),
      );
    }
  }

  private track(work: Promise<void>) {
    this.running.add(work);
    void work.finally(() => this.running.delete(work));
  }

  private async claim() {
    const leaseSeconds = Math.ceil(this.config!.timeoutMs / 1000) + 60;
    const result = await sql<{ id: string; dish_name: string; preferences: string }>`
      update app.ai_draft_requests
      set status = 'running', started_at = now(),
          lease_expires_at = now() + make_interval(secs => ${leaseSeconds})
      where id = (
        select id from app.ai_draft_requests
        where status = 'queued'
          and created_at > now() - make_interval(secs => ${QUEUE_EXPIRY_SECONDS})
        order by created_at
        for update skip locked
        limit 1
      )
      returning id, dish_name, preferences
    `.execute(this.database.db);
    return result.rows[0];
  }

  private async run(job: { id: string; dish_name: string; preferences: string }) {
    const started = Date.now();
    const timeout = AbortSignal.timeout(this.config!.timeoutMs);
    const signal = AbortSignal.any([timeout, this.shutdown.signal]);
    let reply: ProviderReply | undefined;
    let outcome:
      | { status: 'succeeded'; draft: Omit<RecipeInput, 'pricePoints'> }
      | { status: 'failed'; code: AiDraftErrorCode };
    try {
      reply = await this.provider!.complete(
        { dishName: job.dish_name, preferences: job.preferences },
        signal,
      );
      outcome =
        reply.finish === 'refused'
          ? { status: 'failed', code: 'refused' }
          : reply.finish === 'truncated'
            ? { status: 'failed', code: 'invalid_output' }
            : validateDraft(reply.text);
    } catch (error) {
      if (!signal.aborted && !(error instanceof ProviderError)) {
        this.logger.error(`AI provider adapter failed unexpectedly: ${(error as Error).message}`);
      }
      outcome = {
        status: 'failed',
        code: timeout.aborted
          ? 'timeout'
          : this.shutdown.signal.aborted
            ? 'interrupted'
            : 'provider_error',
      };
    }
    const known = reply && reply.inputTokens !== null && reply.outputTokens !== null;
    // Without reported usage (timeout, network failure) the reservation remains the charge.
    const charged = known
      ? costMicros(this.price!, reply!.inputTokens!, reply!.outputTokens!)
      : null;
    const latency = Date.now() - started;
    const finished = await this.database.db
      .updateTable('app.ai_draft_requests')
      .set({
        status: outcome.status,
        draft: outcome.status === 'succeeded' ? JSON.stringify(outcome.draft) : null,
        error_code: outcome.status === 'failed' ? outcome.code : null,
        charged_micros: charged,
        input_tokens: reply?.inputTokens ?? null,
        output_tokens: reply?.outputTokens ?? null,
        latency_ms: latency,
        lease_expires_at: null,
        finished_at: sql<Date>`now()`,
      })
      .where('id', '=', job.id)
      .where('status', '=', 'running')
      .executeTakeFirst();
    // Metadata only: never the dish name, preferences or draft text.
    this.logger.log(
      `AI draft ${job.id}: ${outcome.status}${outcome.status === 'failed' ? ` (${outcome.code})` : ''}, ` +
        `${this.config!.provider}/${this.config!.model}, ${latency} ms, ` +
        `tokens ${reply?.inputTokens ?? '?'}/${reply?.outputTokens ?? '?'}, ` +
        `cost ${charged ?? `≤${this.reservationMicros}`} micro-USD` +
        (Number(finished.numUpdatedRows) === 0 ? ', lease had already expired' : ''),
    );
  }

  /**
   * Running jobs whose lease expired (the process stopped mid-call) fail as interrupted and keep
   * their reservation. Queued jobs that never started within the expiry fail as expired and
   * release it, since they never reached the provider.
   */
  private async recoverStale() {
    await this.database.db
      .updateTable('app.ai_draft_requests')
      .set({
        status: 'failed',
        error_code: 'interrupted',
        lease_expires_at: null,
        finished_at: sql<Date>`now()`,
      })
      .where('status', '=', 'running')
      .where('lease_expires_at', '<', sql<Date>`now()`)
      .execute();
    await this.database.db
      .updateTable('app.ai_draft_requests')
      .set({
        status: 'failed',
        error_code: 'expired',
        charged_micros: 0,
        finished_at: sql<Date>`now()`,
      })
      .where('status', '=', 'queued')
      .where('created_at', '<', sql<Date>`now() - make_interval(secs => ${QUEUE_EXPIRY_SECONDS})`)
      .execute();
  }

  /** Drafts that count against the household: in progress or produced (saved, open or discarded). */
  private async householdUsage(
    executor: Transaction<Database> | DatabaseService['db'],
    householdId: string,
  ) {
    const { used } = await executor
      .selectFrom('app.ai_draft_requests')
      .select(sql<number>`count(*)::int`.as('used'))
      .where('household_id', '=', householdId)
      .where('status', 'in', ['queued', 'running', 'succeeded'])
      .where('created_at', '>', sql<Date>`now() - interval '24 hours'`)
      .executeTakeFirstOrThrow();
    return used;
  }

  /** Provider spend this UTC month: known charges, or the full reservation when unknown. */
  private async monthSpend(trx: Transaction<Database>) {
    const { spent } = await trx
      .selectFrom('app.ai_draft_requests')
      .select(sql<string>`coalesce(sum(coalesce(charged_micros, reserved_micros)), 0)`.as('spent'))
      .where(
        'created_at',
        '>=',
        sql<Date>`date_trunc('month', now() at time zone 'utc') at time zone 'utc'`,
      )
      .executeTakeFirstOrThrow();
    return Number(spent);
  }

  private async lockDraft(trx: Transaction<Database>, householdId: string, draftId: string) {
    if (!isUuid(draftId)) throw new NotFoundException('Draft not found.');
    const draft = await trx
      .selectFrom('app.ai_draft_requests')
      .select(['status', 'saved_recipe_id', 'discarded_at'])
      .where('id', '=', draftId)
      .where('household_id', '=', householdId)
      .forUpdate()
      .executeTakeFirst();
    if (!draft) throw new NotFoundException('Draft not found.');
    return draft;
  }

  private baseQuery(executor: Transaction<Database> | DatabaseService['db'] = this.database.db) {
    return executor
      .selectFrom('app.ai_draft_requests as d')
      .innerJoin('app.user_profiles as p', 'p.id', 'd.created_by')
      .select([
        'd.id',
        'd.status',
        'd.dish_name as dishName',
        'd.preferences',
        'd.model',
        'd.error_code as errorCode',
        sql<DraftRow['draft']>`d.draft`.as('draft'),
        'd.saved_recipe_id as savedRecipeId',
        'd.discarded_at as discardedAt',
        'd.created_at as createdAt',
        'd.finished_at as finishedAt',
        'p.display_name as createdBy',
      ]);
  }

  private async read(
    executor: Transaction<Database> | DatabaseService['db'],
    householdId: string,
    draftId: string,
  ) {
    if (!isUuid(draftId)) throw new NotFoundException('Draft not found.');
    const row = await this.baseQuery(executor)
      .where('d.id', '=', draftId)
      .where('d.household_id', '=', householdId)
      .executeTakeFirst();
    if (!row) throw new NotFoundException('Draft not found.');
    return row;
  }

  private present(row: DraftRow) {
    const { discardedAt, errorCode, ...rest } = row;
    return {
      ...rest,
      discarded: discardedAt !== null,
      errorCode,
      errorMessage: errorCode ? ERROR_MESSAGES[errorCode] : null,
    };
  }
}

/**
 * Repairs two near-misses seen in the 2026-09-27 evaluation without inventing an amount: a
 * quantity written as the text "null" (or blank) means no quantity, and a unit without a
 * quantity (such as "a pinch of salt, to taste") loses its unit and keeps its note. Anything
 * else is left for the normal validation to accept or reject.
 */
function normalizeAmounts(ingredients: unknown) {
  if (!Array.isArray(ingredients)) return ingredients;
  return ingredients.map((line: unknown) => {
    if (!line || typeof line !== 'object') return line;
    const next = { ...(line as Record<string, unknown>) };
    if (typeof next.quantity === 'string' && /^\s*(null)?\s*$/i.test(next.quantity)) {
      next.quantity = null;
    }
    if ((next.quantity === null || next.quantity === undefined) && next.unit) {
      if (!next.note) next.note = 'to taste';
      next.unit = null;
    }
    return next;
  });
}

/** Parses model text and applies the same rules as a manually entered recipe. */
export function validateDraft(
  text: string,
):
  | { status: 'succeeded'; draft: Omit<RecipeInput, 'pricePoints'> }
  | { status: 'failed'; code: 'invalid_output' } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { status: 'failed', code: 'invalid_output' };
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return { status: 'failed', code: 'invalid_output' };
  }
  try {
    // Price stays the household's choice; the model is never asked for one.
    const { name, description, servings, steps, ingredients } = parseRecipeInput({
      ...parsed,
      ingredients: normalizeAmounts((parsed as { ingredients?: unknown }).ingredients),
      pricePoints: 0,
    });
    const draft = { name, description, servings, steps, ingredients };
    if (draft.ingredients.length === 0 || draft.steps.length === 0) {
      return { status: 'failed', code: 'invalid_output' };
    }
    return { status: 'succeeded', draft };
  } catch {
    return { status: 'failed', code: 'invalid_output' };
  }
}
