import {
  BadRequestException,
  HttpStatus,
  HttpException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { sql, type Transaction } from 'kysely';
import { DatabaseService, type Database } from './database.service.js';
import { HouseholdsService } from './households.service.js';
import { isUuid } from './security.js';
import {
  buildChecklist,
  buildShoppingList,
  parseLineId,
  present,
  rational,
  type AllocationRow,
  type SnapshotLine,
} from './shopping.js';

export const PURCHASE_HISTORY_LIMIT = 100;
/** Serializes checks within one household (ADR 0009); other households are unaffected. */
const lockKey = (householdId: string) => sql`hashtextextended(${'shopping:' + householdId}, 0)`;

type Scope = { from?: string; to?: string };
type Executor = Transaction<Database> | DatabaseService['db'];

export function parsePurchase(body: unknown) {
  const input = (body ?? {}) as Record<string, unknown>;
  if (typeof input.requestId !== 'string' || !isUuid(input.requestId)) {
    throw new BadRequestException(
      'requestId must be a UUID generated by the client for this check.',
    );
  }
  const line = parseLineId(input.lineId);
  if (!line) throw new BadRequestException('lineId does not identify a shopping line.');
  if (typeof input.token !== 'string' || !input.token || input.token.length > 64) {
    throw new BadRequestException('token is required.');
  }
  return {
    requestId: input.requestId.toLowerCase(),
    lineId: input.lineId as string,
    token: input.token,
    scope: parseScope(input.from, input.to),
  };
}

function changed(): never {
  throw new HttpException(
    {
      statusCode: HttpStatus.CONFLICT,
      code: 'shopping_changed',
      message: 'The shopping list changed since you loaded it. Refresh and check again.',
    },
    HttpStatus.CONFLICT,
  );
}

const DATE = /^\d{4}-\d{2}-\d{2}$/;

export function parseScope(from: unknown, to: unknown) {
  const check = (value: unknown, name: string) => {
    if (value === undefined || value === '') return undefined;
    if (typeof value !== 'string' || !DATE.test(value) || Number.isNaN(Date.parse(value))) {
      throw new BadRequestException(`${name} must be a date like 2026-10-03.`);
    }
    return value;
  };
  const scope = { from: check(from, 'from'), to: check(to, 'to') };
  if (scope.from && scope.to && scope.from > scope.to) {
    throw new BadRequestException('from must not be after to.');
  }
  return scope;
}

/**
 * Shopping demand for a household, derived only from pending order snapshots. One SQL statement
 * reads every row, so both views share one consistent database snapshot.
 */
@Injectable()
export class ShoppingService {
  constructor(
    private readonly database: DatabaseService,
    private readonly households: HouseholdsService,
  ) {}

  async list(userId: string, householdId: string, scope: Scope) {
    await this.households.requireMember(userId, householdId);
    // Demand and purchases are read from one snapshot, so the checklist matches the views.
    return this.database.db
      .transaction()
      .setIsolationLevel('repeatable read')
      .execute(async (trx) => {
        const rows = await this.demand(trx, householdId, scope);
        const allocations = await this.allocations(trx, householdId, rows);
        const list = buildShoppingList(rows);
        return {
          scope: { from: scope.from ?? null, to: scope.to ?? null },
          generatedAt: rows[0]?.generatedAt ?? new Date(),
          orderCount: new Set(rows.map((row) => row.orderId)).size,
          ...list,
          checklist: buildChecklist(rows, allocations).map((line) => {
            // Allocation details stay on the server.
            const shown: Partial<typeof line> = { ...line };
            delete shown.outstanding;
            delete shown.total;
            return shown;
          }),
        };
      });
  }

  /**
   * Records that a member bought what the list showed for one line, allocating the exact
   * remaining amount to each pending order item in scope. A stale token (another member checked
   * it, or an order changed) records nothing and returns 409 shopping_changed.
   */
  async purchase(userId: string, householdId: string, input: ReturnType<typeof parsePurchase>) {
    return this.database.db.transaction().execute(async (trx) => {
      await this.households.requireMember(userId, householdId, trx, true);
      await sql`select pg_advisory_xact_lock(${lockKey(householdId)})`.execute(trx);
      const existing = await trx
        .selectFrom('app.shopping_purchases')
        .select('id')
        .where('household_id', '=', householdId)
        .where('request_id', '=', input.requestId)
        .executeTakeFirst();
      if (existing) return this.history(trx, householdId, existing.id).then(([row]) => row!);

      const rows = await this.demand(trx, householdId, input.scope);
      const allocations = await this.allocations(trx, householdId, rows);
      const line = buildChecklist(rows, allocations).find((entry) => entry.lineId === input.lineId);
      if (!line || line.token !== input.token || line.outstanding.length === 0) changed();

      const inserted = await trx
        .insertInto('app.shopping_purchases')
        .values({
          household_id: householdId,
          ingredient_key: line.key,
          form_key: parseLineId(line.lineId)!.formKey,
          family: line.family,
          name: line.name,
          form: line.form,
          quantity_num: line.total ? line.total.n.toString() : null,
          quantity_den: line.total ? line.total.d.toString() : null,
          request_id: input.requestId,
          created_by: userId,
        })
        .returning('id')
        .executeTakeFirstOrThrow();
      try {
        await trx
          .insertInto('app.shopping_allocations')
          .values(
            line.outstanding.map(({ itemId, quantity }) => ({
              household_id: householdId,
              purchase_id: inserted.id,
              order_item_id: itemId,
              quantity_num: quantity ? quantity.n.toString() : null,
              quantity_den: quantity ? quantity.d.toString() : null,
            })),
          )
          .execute();
      } catch (error) {
        // A dish was removed from its order after the demand was read.
        if ((error as { code?: string }).code === '23503') changed();
        throw error;
      }
      await trx
        .insertInto('app.audit_events')
        .values({
          household_id: householdId,
          actor_id: userId,
          entity_type: 'shopping_purchase',
          entity_id: inserted.id,
          action: 'check',
          revision: 1,
        })
        .execute();
      const [created] = await this.history(trx, householdId, inserted.id);
      return created!;
    });
  }

  /** Voids a whole purchase once; it stays in history, marked as undone. */
  async undo(userId: string, householdId: string, purchaseId: string) {
    return this.database.db.transaction().execute(async (trx) => {
      await this.households.requireMember(userId, householdId, trx, true);
      await sql`select pg_advisory_xact_lock(${lockKey(householdId)})`.execute(trx);
      if (!isUuid(purchaseId)) throw new NotFoundException('Purchase not found.');
      const purchase = await trx
        .selectFrom('app.shopping_purchases')
        .select(['id', 'undone_at'])
        .where('household_id', '=', householdId)
        .where('id', '=', purchaseId)
        .forUpdate()
        .executeTakeFirst();
      if (!purchase) throw new NotFoundException('Purchase not found.');
      if (!purchase.undone_at) {
        await trx
          .updateTable('app.shopping_purchases')
          .set({ undone_by: userId, undone_at: sql<Date>`now()` })
          .where('id', '=', purchaseId)
          .execute();
        await trx
          .insertInto('app.audit_events')
          .values({
            household_id: householdId,
            actor_id: userId,
            entity_type: 'shopping_purchase',
            entity_id: purchaseId,
            action: 'undo',
            revision: 2,
          })
          .execute();
      }
      const [row] = await this.history(trx, householdId, purchaseId);
      return row!;
    });
  }

  async listPurchases(userId: string, householdId: string) {
    await this.households.requireMember(userId, householdId);
    return this.history(this.database.db, householdId);
  }

  private async history(executor: Executor, householdId: string, purchaseId?: string) {
    let query = executor
      .selectFrom('app.shopping_purchases as p')
      .innerJoin('app.user_profiles as c', 'c.id', 'p.created_by')
      .leftJoin('app.user_profiles as u', 'u.id', 'p.undone_by')
      .select([
        'p.id',
        'p.name',
        'p.form',
        'p.family',
        'p.quantity_num',
        'p.quantity_den',
        'p.created_at as purchasedAt',
        'c.display_name as purchasedBy',
        'p.undone_at as undoneAt',
        'u.display_name as undoneBy',
      ])
      .where('p.household_id', '=', householdId);
    if (purchaseId) query = query.where('p.id', '=', purchaseId);
    const rows = await query
      .orderBy('p.created_at', 'desc')
      .orderBy('p.id')
      .limit(PURCHASE_HISTORY_LIMIT)
      .execute();
    return rows.map(({ quantity_num, quantity_den, ...row }) => ({
      ...row,
      unquantified: quantity_num === null,
      amount:
        quantity_num === null || quantity_den === null
          ? null
          : present(rational(BigInt(quantity_num), BigInt(quantity_den)), row.family),
    }));
  }

  /** Active allocations to the given demand rows' order items. */
  private async allocations(
    executor: Executor,
    householdId: string,
    rows: { itemId: string }[],
  ): Promise<AllocationRow[]> {
    const itemIds = [...new Set(rows.map((row) => row.itemId))];
    if (itemIds.length === 0) return [];
    const found = await executor
      .selectFrom('app.shopping_allocations as a')
      .innerJoin('app.shopping_purchases as p', (join) =>
        join.onRef('p.id', '=', 'a.purchase_id').onRef('p.household_id', '=', 'a.household_id'),
      )
      .innerJoin('app.user_profiles as u', 'u.id', 'p.created_by')
      .select([
        'a.purchase_id',
        'a.order_item_id',
        'a.quantity_num',
        'a.quantity_den',
        'p.ingredient_key',
        'p.form_key',
        'p.family',
        'p.created_at',
        'u.display_name',
      ])
      .where('a.household_id', '=', householdId)
      .where('a.order_item_id', 'in', itemIds)
      .where('p.undone_at', 'is', null)
      .execute();
    return found.map((row) => ({
      purchaseId: row.purchase_id,
      itemId: row.order_item_id,
      key: row.ingredient_key,
      formKey: row.form_key,
      family: row.family,
      quantity:
        row.quantity_num === null || row.quantity_den === null
          ? null
          : rational(BigInt(row.quantity_num), BigInt(row.quantity_den)),
      purchasedBy: row.display_name,
      purchasedAt: row.created_at,
    }));
  }

  private async demand(executor: Executor, householdId: string, scope: Scope) {
    let query = executor
      .selectFrom('app.meal_order_items as i')
      .innerJoin('app.meal_orders as o', (join) =>
        join.onRef('o.id', '=', 'i.order_id').onRef('o.household_id', '=', 'i.household_id'),
      )
      .select([
        'o.id as orderId',
        sql<string>`to_char(o.meal_date, 'YYYY-MM-DD')`.as('mealDate'),
        sql<string>`to_char(o.meal_time, 'HH24:MI')`.as('mealTime'),
        'o.scheduled_at as scheduledAt',
        'i.id as itemId',
        'i.recipe_name as recipeName',
        'i.servings',
        'i.recipe_servings as recipeServings',
        sql<SnapshotLine[]>`i.ingredients`.as('ingredients'),
        sql<Date>`now()`.as('generatedAt'),
      ])
      .where('o.household_id', '=', householdId)
      .where('o.status', '=', 'pending');
    if (scope.from) query = query.where('o.meal_date', '>=', scope.from);
    if (scope.to) query = query.where('o.meal_date', '<=', scope.to);
    return query
      .orderBy('o.scheduled_at')
      .orderBy('o.created_at')
      .orderBy('o.id')
      .orderBy('i.position')
      .execute();
  }
}
